
# docker-compose.devk8s.yml (Development overrides)
services:
  backend:
    build:
      target: devk8s  # Override to use development stage
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: "true"
       # Database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Auth0
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
      AUTH0_M2M_CLIENT_ID: ${AUTH0_M2M_CLIENT_ID}
      AUTH0_M2M_CLIENT_SECRET: ${AUTH0_M2M_CLIENT_SECRET}
    
  frontend:
    build:
      target: devk8s  # Override to use development stage  
    # command: npm run dev
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
       # Auth0
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_SCOPE: ${AUTH0_SCOPE}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      # App config
      APP_BASE_URL: ${APP_BASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      BACkEND_URL: ${BACkEND_URL}
  
  postgres:
      ports:
        - "5433:5432" 