# Default values for k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/


ingress:
  enabled: true

frontend:
  name: kaban-frontend
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1001
  
  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

backend: 
  name: kaban-backend
  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1001
  
  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

serviceAccount:
  create: false

service: 
  port: 80

httpRoute:
  enabled: false

  