{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
stringData:  # Use stringData for plain text (K8s encodes to base64 automatically)
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

